/**
 * Generate the extension's category lookup from the mapping layer.
 *
 *   npm run crosslist:generate-map
 *
 * lib/crosslist is TypeScript with a rule engine; the extension is plain
 * browser JS and cannot import it. Rather than port the rules - two copies
 * of the same logic drifting apart is how a listing ends up in the wrong
 * category - this emits a flat lookup keyed on the exact
 * "category|subcategory" pairs the catalogue actually contains.
 *
 * That keeps one source of truth. Re-run it whenever inventory gains a
 * category the map does not cover; unmapped pairs are listed at the end so
 * it is obvious when that has happened.
 */

import { createClient } from '@supabase/supabase-js'
import { writeFileSync } from 'node:fs'

try {
  process.loadEnvFile('.env.local')
} catch {
  /* ambient env */
}

const { mapCategory } = await import('../lib/crosslist/categories')
const { CROSSLIST_PLATFORMS } = await import('../lib/crosslist/types')

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { persistSession: false, autoRefreshToken: false } },
)

type Row = { category: string | null; subcategory: string | null }

const rows: Row[] = []
for (let from = 0; ; from += 1000) {
  const { data, error } = await supabase
    .from('inventory')
    .select('category, subcategory')
    .range(from, from + 999)
  if (error) throw new Error(error.message)
  rows.push(...((data ?? []) as Row[]))
  if (!data || data.length < 1000) break
}

/** The key the extension will look up. */
const keyOf = (r: Row) => `${r.category ?? ''}|${r.subcategory ?? ''}`

const pairs = new Map<string, Row>()
for (const row of rows) pairs.set(keyOf(row), row)

const maps: Record<string, Record<string, string[]>> = {}
const unmapped = new Set<string>()

for (const platform of CROSSLIST_PLATFORMS) {
  maps[platform] = {}
  for (const [key, row] of pairs) {
    const mapped = mapCategory(platform, row.category, row.subcategory)
    if (mapped) maps[platform][key] = mapped.path
    else unmapped.add(key)
  }
}

const covered = Object.values(maps).map((m) => Object.keys(m).length)

const banner = `// GENERATED by scripts/generate-category-map.mts - do not edit by hand.
//
// Flat lookup from an item's exact "category|subcategory" to each platform's
// category path. Generated from lib/crosslist so the rules live in one place
// rather than being ported into browser JS and drifting.
//
// Covers ${pairs.size} distinct category pairs in the catalogue.
// Re-run \`npm run crosslist:generate-map\` after importing new inventory.
`

const body = `(function () {
  "use strict";
  globalThis.AnkCategoryMap = ${JSON.stringify(maps, null, 2)};

  /** Path for this item, or null when the category has no home there. */
  globalThis.AnkCategoryMap.lookup = function (platform, category, subcategory) {
    const table = globalThis.AnkCategoryMap[platform];
    if (!table) return null;
    return table[(category || "") + "|" + (subcategory || "")] || null;
  };
})();
`

writeFileSync('extension/lib/category-map.generated.js', banner + body, 'utf8')

console.log(`distinct category pairs   ${pairs.size}`)
CROSSLIST_PLATFORMS.forEach((p, i) =>
  console.log(`  ${p.padEnd(10)} mapped   ${covered[i]}`),
)
console.log(`\nunmapped pairs            ${unmapped.size}`)
for (const key of Array.from(unmapped).slice(0, 10)) {
  console.log(`  ${key.split('|')[0].slice(0, 70)}`)
}
if (unmapped.size > 10) console.log(`  ... and ${unmapped.size - 10} more`)
console.log('\nwrote extension/lib/category-map.generated.js')
